#!/usr/bin/env bash

# Include lib for printing with colors
# shellcheck source=/dev/null
source $DOTFILES_PATH/bash/libs/print.sh

ACTION="$1"
KBD="$2"

check_keyboard_type() {
  if [[ $KBD != "ergodox" && $KBD != "dactyl" && $KBD != "atreus62" ]]; then
    print::fail "You must specify a supported keyboard type"
    exit 1
  fi
}

case $ACTION in
  "build-images" )
      docker-compose build
    ;;

  "build" )
      check_keyboard_type

      sudo rm -rf ./dist

      docker-compose run $KBD
      sudo chown -R taylon dist
    ;;

  "flash" )
      check_keyboard_type

      if [[ $KBD == "ergodox" ]]; then
        hex_file="ergodox_ez_taylon.hex"
      elif [[ $KBD == "dactyl" ]]; then
        hex_file="handwired_dactyl_taylon.hex"
      elif [[ $KBD == "atreus62" ]]; then
        hex_file="atreus62_taylon.hex"
      fi

      teensy-loader-cli -v -mmcu=atmega32u4 -w ./dist/$hex_file
    ;;
esac
