#!/usr/bin/env bash
# shellcheck source=/dev/null

source "${DOTFILES_PATH}/bash/libs/print.sh"

# docker-compose run --rm "$KBD"
# sudo chown -R taylon dist

ACTION="$1"
KBD="$2"

DOCKER_IMAGE="qmk_keymaps_builder"
QMK_KEYMAPS_FOLDER="${DOTFILES_PATH}/keyboard/qmk_keymaps"
KEYBOARDS_PATH="${QMK_KEYMAPS_FOLDER}/keyboards"
DIST_PATH="${QMK_KEYMAPS_FOLDER}/dist"

check_keyboard_type() {
  if [[ -z $KBD || ! -d "${KEYBOARDS_PATH}/${KBD}"  ]]; then
    print::fail "You must specify a supported keyboard type"
    exit 1
  fi
}

clean() {
  # On Linux Docker sets root user for files created in volumes
  # I won't bother with this right now so let's just use sudo
  # sudo rm -rf "$DIST_PATH"
  rm -rf "$DIST_PATH"
}

case $ACTION in
  "build-image" )
      docker build -t $DOCKER_IMAGE .
    ;;

  "build" )
      check_keyboard_type
      clean

      target=default
      make_command=(make "${KBD}":"${target}")
      # make_command=(make "${KBD}":"${target}":bin)

      if [[ $(uname) == "Darwin" ]]; then
        make_command=("${make_command[@]}" "EXTRAFLAGS=-D IS_MACOS")
      fi

      keymaps_path="/qmk/keyboards/$KBD/keymaps"
      # shellcheck disable=SC2086
      docker run --rm \
        -v "${KEYBOARDS_PATH}/$KBD/:${keymaps_path}/${target}" \
        -v "${QMK_KEYMAPS_FOLDER}/shared:${keymaps_path}/shared/" \
        -v "${QMK_KEYMAPS_FOLDER}/dist/:/qmk/.build/" \
        qmk_keymaps_builder \
        "${make_command[@]}"
        # make alf/dc60:default
        # /bin/bash
        # make alf/dc60:default
        # /bin/bash

      # On Linux Docker sets root user for files created in volumes
      # I won't bother with this right now so let's just use sudo
      # sudo chown -R "$(whoami)":"$(whoami)" "$DIST_PATH"
    ;;

  "flash" )
      check_keyboard_type

      hex_file="${DIST_PATH}/${KBD}_default.hex"

      if [[ ! -e $hex_file && ! -s $hex_file ]]; then
        print::fail "Hex file does not exist or is empty"
        exit 1
      fi

      teensy-loader-cli -v -mmcu=atmega32u4 -w "$hex_file"
    ;;
esac
