#!/bin/sh

# Set a fast key repeat rate
xset r rate 200 25

nvidia-settings --load-config-only &
redshift &

# XRANDR_OUTPUT=$(xrandr | grep " connected " | awk '{ print$1 }')
# xrandr --output "$XRANDR_OUTPUT" --mode 5120x1440

xsetroot -solid "#282c34"

xrdb -merge ~/.Xresources &&
  exec i3
