set guifont=Operator\ Mono\ SSm:h18
set guioptions= " Remove all UI elements like toolbars and scrollbars

set linespace=10 " Set line height
set macligatures " Enable font ligatures

" Keep the cursor always in the middle
augroup VCenterCursor
 au!
 au BufEnter,WinEnter,WinNew,VimResized *,*.*
      \ let &scrolloff=winheight(win_getid())/2
augroup END

" MacVim
if has("gui_macvim")

  " Unbind useless bs
  macmenu File.Print key=<nop>
  macmenu File.Save key=<nop>
  macmenu File.Save\ All key=<nop>
  macmenu File.Save\ As\.\.\. key=<nop>
  macmenu File.New\ Tab key=<nop>

  " Let's try this temporarily until we have a better
  " solution for this that does not involve D mappings
  noremap  <D-Left> <Home>
  noremap! <D-Left> <Home>
  noremap  <M-Left> <C-Left>
  noremap! <M-Left> <C-Left>

  noremap  <D-Right> <End>
  noremap! <D-Right> <End>
  noremap  <M-Right> <C-Right>
  noremap! <M-Right> <C-Right>

  noremap  <D-Up> <C-Home>
  inoremap <D-Up> <C-Home>

  noremap  <D-Down> <C-End>
  inoremap <D-Down> <C-End>

  inoremap <M-BS> <C-w>
  inoremap <D-BS> <C-u>

endif

" Cursor settings
highlight vCursor guifg=white guibg=#e5c07b
set guicursor+=v:ver100-vCursor
set guicursor+=a:blinkon0
