filetype plugin indent on

syntax on
" if has('syntax') && !exists('g:syntax_on')
"   syntax enable
" endif

" Disable cmd_opt movement mappings because they
" conflict with other stuff, unfortunatelly this needs
" to live in vimrc not gvimrc
if has("gui_macvim")
  let macvim_skip_cmd_opt_movement = 1
endif

if has("termguicolors")
  set termguicolors " Enable 24-bit (true-color) mode
endif

" Speed up viewport scrolling
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>


let g:clever_f_mark_char_color = "CleverFMark"


source ~/.vim/keymaps.vim
source ~/.vim/plugins.vim
source ~/.vim/colorscheme.vim

" For debugging syntax stuff
" function! SynStack()
"   echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
" endfunc
" set statusline+=%{SynStack()}

