#!/usr/bin/env bash

# gsettings list-recursively |grep "<Alt>space"

# Set Colemak Mod-DH as the default keyboard layout
gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us+colemak_moddh_matrix'), ('xkb', 'us+alt-intl')]"

# Swap win/alt/ctrl and caps/backspace
gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:swap_lalt_lctl_lwin', 'caps:backspace']"

# Set ctrl-tab to switch windows (instead of alt-tab)
gsettings set org.gnome.desktop.wm.keybindings switch-applications "['<Control>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "['<Shift><Control>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-group "['<Control>Above_Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-group-backward "['<Shift><Control>Above_Tab']"

# Remap Alt+F4
gsettings set org.gnome.desktop.wm.keybindings close "['<Control>q']"

# Disable lock screen shortcut
gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver ""

# Set ctrl-space as a keybind to gnome-shell's overview
gsettings set org.gnome.mutter overlay-key ""
gsettings set org.gnome.shell.keybindings toggle-overview "['<Control>space']"
gsettings set org.gnome.desktop.wm.keybindings panel-main-menu "['<Control>space']"

# Limit Alt-Tab to current workspace
# gsettings set org.gnome.shell.app-switcher current-workspace-only true

# Atom will use Super-Left/Right and Super-Shift-Left/Right to subword navigation
# so lets disable everything that uses it the Window Manager
gsettings set org.gnome.mutter.keybindings toggle-tiled-left "['<Alt><Control><Super>Left']"
gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Alt><Control><Super>Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-left []
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-right []

# Gnome-terminal (We don't use it anymore but let's keep it here just in case)
# gsettings set org.gnome.terminal.legacy.keybindings close-tab "<Primary>w"
# gsettings set org.gnome.terminal.legacy.keybindings new-tab "<Primary>t"
# gsettings set org.gnome.terminal.legacy.keybindings next-tab "<Primary>braceright"
# gsettings set org.gnome.terminal.legacy.keybindings prev-tab "<Primary>bracerleft"
