#!/usr/bin/env bash

# Install packages from arch_pkglist.txt

# Setup symlinks

# Improve font-rendering
# https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671

# Docker Setup
sudo systemctl start docker.service
sudo systemctl enable docker.service
sudo gpasswd -a taylon docker

# Reminders of last setup

# - Add the following to /etc/modprobe.d/50-blacklist-kvm.conf since we don't need it 
#   - blacklist kvm
#   - blacklist kvm_intel
#   - blacklist kvm_amd

