#!/usr/bin/env bash

# Install packages from arch_pkglist.txt

# Setup symlinks

# Improve font-rendering
# https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671

# SSH Agent
echo 'SSH_AUTH_SOCK DEFAULT="${XDG_RUNTIME_DIR}/ssh-agent.socket"' >'$HOME'/.pam_environment
systemctl enable ssh-agent --user

# Docker Setup
sudo systemctl start docker
sudo systemctl enable docker
sudo gpasswd -a taylon docker

# Reminders of last setup

# - Add the following to /etc/modprobe.d/50-blacklist-kvm.conf since we don't need it 
#   - blacklist kvm
#   - blacklist kvm_intel
#   - blacklist kvm_amd

# - Saved nvidia xorg settings manually to /etc/X11/xorg.conf.d
