#!/usr/bin/env bash

# Systemd (Arch only)
ln -s $DOTFILES_PATH/systemd $HOME/.config/systemd

# Tilix (Arch only)
# ln -s $DOTFILES_PATH/tilix $HOME/.config/tilix

# Hyper
ln -s $DOTFILES_PATH/hyper/.hyper_linux.js $HOME/.hyper.js

# Xmodmap - It fixes the issue with capslock not keyrepeating
ln -s $DOTFILES_PATH/keyboard/arch/Xmodmap $HOME/.Xmodmap

# Customize mouse buttons
ln -s $DOTFILES_PATH/mouse/arch/imwheelrc $HOME/.imwheelrc
