#include QMK_KEYBOARD_H
#include "version.h"

#include "./shared/custom_keys.h"

// Layers
enum {
  BASE = 0,
  NUMPAD,
  SYMBOLS,
  HUB_LAYER,
  RESET_LAYER,
  STARCRAFT,
  POE,
};

// Tap Dance
enum {
  // Layers
  TD_LAYER_HUB = 0,

  // Symbols
  TD_PRN,
  TD_CBR,
  TD_BRACKET,
  TD_COPY_CUT,
};

qk_tap_dance_action_t tap_dance_actions[] = {
  // Layers
  [TD_LAYER_HUB] = ACTION_TAP_DANCE_DUAL_ROLE(KC_ESCAPE, HUB_LAYER),

  // Symbols
  [TD_PRN] = ACTION_TAP_DANCE_DOUBLE(KC_LPRN, KC_RPRN),
  [TD_CBR] = ACTION_TAP_DANCE_DOUBLE(KC_LCBR, KC_RCBR),
  [TD_BRACKET] = ACTION_TAP_DANCE_DOUBLE(KC_LBRACKET, KC_RBRACKET),

#ifdef IS_MACOS
  [TD_COPY_CUT] = ACTION_TAP_DANCE_DOUBLE(LGUI(KC_C), LGUI(KC_X)),
#else
  [TD_COPY_CUT] = ACTION_TAP_DANCE_DOUBLE(LCTL(KC_C), LCTL(KC_X)),
#endif
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [BASE] = LAYOUT_dactyl(
    // Left hand
    KC_TRNS, CK_Music, CK_Browser, CK_Vim, CK_Terminal, CK_Chat, 
    KC_DELETE, KC_Q, KC_W, LAYER_NUMPAD_F, KC_P, KC_B,
    KC_TAB, HM_A, HM_R, HM_S, KC_T, KC_G,
    OS_COPY_CUT, KC_Z, KC_X, KC_C, KC_D, KC_V,
    OS_PASTE, KC_TRNS, KC_TRNS, KC_LEFT, KC_RIGHT,

    KC_GESC, KC_MEDIA_PLAY_PAUSE,
    KC_F8,
    KC_BSPACE, OSM(MOD_LSFT), KC_TRNS,

    // Right hand
    KC_TRNS, KC_TRNS, CK_Leader, CK_FileNavigation, KC_TRNS, CK_I3,
    KC_J, KC_L, KC_U, KC_Y, KC_SCOLON, KC_TRNS,
    KC_M, KC_N, HM_E, HM_I, HM_O, KC_QUOTE,
    KC_K, KC_H, KC_COMMA, KC_DOT, KC_SLASH, KC_MINUS,
    KC_UP, KC_DOWN, CK_Back, CK_Forward, KC_TRNS,

    LAYER_HUB, KC_ENTER,
    TG(STARCRAFT),
    TG(POE), OSL(SYMBOLS), KC_SPACE
  ),

  [NUMPAD] = LAYOUT_dactyl(
    // Left hand
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LSHIFT, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

    KC_TRNS, KC_TRNS,
    KC_TRNS,
    KC_BSPACE, KC_ENTER, KC_TRNS,

    // Right hand
    KC_TRNS, KC_TRNS, KC_TRNS, KC_PERC, KC_KP_SLASH, KC_TRNS,
    KC_TRNS, KC_7, KC_8, KC_9, KC_KP_ASTERISK, KC_TRNS,
    KC_MS_WH_UP, KC_4, KC_5, KC_6, KC_KP_MINUS, KC_TRNS,
    KC_MS_WH_DOWN, KC_1, KC_2, KC_3, KC_KP_PLUS, KC_TRNS,
    KC_0, KC_COMMA, KC_DOT, KC_EQUAL, KC_TRNS,

    KC_TRNS, KC_TRNS,
    KC_TRNS,
    KC_TRNS, LEADER, KC_SPACE
  ),

  [SYMBOLS] = LAYOUT_dactyl(
    // Left hand
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_PERC, KC_AT, SYMBOL_CBR, KC_DLR, KC_PIPE,
    KC_TRNS, KC_HASH, KC_TILD, SYMBOL_PRN, KC_EQUAL, KC_PLUS,
    KC_TRNS, KC_CIRC, KC_EXLM, SYMBOL_BRACKET, KC_AMPR, KC_ASTR,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_BSLASH, KC_GRAVE,

    KC_TRNS, KC_TRNS,
    KC_TRNS,
    KC_BSPACE, KC_ENTER, KC_TRNS,

    // Right hand
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_LSHIFT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

    KC_TRNS, KC_TRNS,
    KC_TRNS,
    KC_TRNS, LEADER, KC_SPACE
  ),

  [HUB_LAYER] = LAYOUT_dactyl(
    // Left hand
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_A, TO(RESET_LAYER), KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

    KC_TRNS, KC_TRNS,
    KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS,

    // Right hand
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

    KC_TRNS, KC_TRNS,
    TO(BASE),
    KC_TRNS, KC_TRNS, KC_TRNS
  ),

  [STARCRAFT] = LAYOUT_dactyl(
    // Left hand
    KC_1, KC_2, KC_7, KC_4, KC_5, KC_6,
    KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T,
    KC_P, KC_A, KC_S, KC_D, KC_F, KC_G,
    KC_O, KC_Z, KC_X, KC_C, KC_V, KC_B,
    KC_I, KC_U, KC_Y, KC_L, KC_K,

    KC_SPACE, KC_F10,
    KC_TRNS,
    OSM(MOD_LSFT), OSM(MOD_LCTL), KC_TRNS,

    // Right hand
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_J, KC_L, LAYER_SYMBOL_U, KC_Y, KC_SCOLON, KC_TRNS,
    KC_M, HM_N, HM_E, HM_I, HM_O, KC_QUOTE,
    KC_K, KC_H, KC_COMMA, KC_DOT, KC_SLASH, KC_MINUS,
    KC_UP, KC_DOWN, GENERAL_TAB_NAV, GENERAL_TAB_RECENT, KC_TRNS,

    LAYER_HUB, KC_CAPSLOCK,
    KC_TRNS,
    KC_TRNS, LEADER, KC_SPACE
  ),

  [POE] = LAYOUT_dactyl(
    // Left hand
    KC_6, KC_7, KC_8, KC_9, KC_PERC, KC_AT,
    KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T,
    KC_P, KC_A, KC_S, KC_D, KC_F, KC_G,
    KC_O, KC_Z, KC_X, KC_C, KC_V, KC_B,
    KC_I, KC_U, KC_Y, KC_L, KC_K,

    KC_H, KC_F10,
    KC_SCOLON,
    KC_SPACE, KC_M, KC_ESC,

    // Right hand
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_J, KC_L, LAYER_SYMBOL_U, KC_Y, KC_SCOLON, KC_TRNS,
    KC_M, HM_N, HM_E, HM_I, HM_O, KC_QUOTE,
    KC_K, KC_H, KC_COMMA, KC_DOT, KC_SLASH, KC_MINUS,
    KC_UP, KC_DOWN, GENERAL_TAB_NAV, GENERAL_TAB_RECENT, KC_TRNS,

    LAYER_HUB, KC_CAPSLOCK,
    KC_TRNS,
    KC_TRNS, LEADER, KC_SPACE
  ),

  [RESET_LAYER] = LAYOUT_dactyl(
    // Left hand
    KC_A, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

    KC_TRNS, KC_TRNS,
    KC_TRNS,
    RESET, KC_TRNS, KC_TRNS,

    // Right hand
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

    KC_TRNS, KC_TRNS,
    TO(BASE),
    KC_TRNS, KC_TRNS, KC_TRNS
  ),
};
