#!/usr/bin/env bash

# Install packages from arch_pkglist.txt

# Setup Gnome

# Setup symlinks

# Load Tilix configuration
dconf load /com/gexperts/Tilix/ < ~/Development/dotfiles/tilix/tilix.conf

# Improve font-rendering
https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671
