#!/usr/bin/env bash

DEV_PATH="$HOME/Development"
DOTFILES_PATH="$DEV_PATH/dotfiles"

# Create VIM's backup, swap and undo history folders
mkdir $DOTFILES_PATH/vim/.backups
mkdir $DOTFILES_PATH/vim/.swaps
mkdir $DOTFILES_PATH/vim/.undo

# Create folder for N
mkdir -p $HOME/.node/bin

# Setup SSH keys
# Host github.com
#   IdentityFile ~/.ssh/

# Create Fisherman's plugins folder
mkdir $HOME/.fisherman_plugins

# NPM stuff - Do this after setting up N/Node
npm install -g bash-language-server
npm install -g trash-cli
