#!/usr/bin/env bash

DEV_PATH="$HOME/Development"
DOTFILES_PATH="$DEV_PATH/dotfiles"

# Create private fish file
touch "$HOME"/.config/fish/private.fish

# Create VIM's backup, swap and undo history folders
mkdir $DOTFILES_PATH/vim/.backups
mkdir $DOTFILES_PATH/vim/.swaps
mkdir $DOTFILES_PATH/vim/.undo

# Create folder for N
mkdir -p $HOME/.node/bin

# Setup SSH keys at ~/.ssh/config
# Host github.com
#   IdentityFile ~/.ssh/...

# NPM stuff - Do this after setting up N/Node
yarn config set prefix $HOME/.node/

yarn global add bash-language-server
yarn global add trash-cli
yarn global add all-the-package-names
