#!/usr/bin/env sh

DEV_PATH="$HOME/Development"
DOTFILES_PATH="$DEV_PATH/dotfiles"

# Bash
ln -s "$DOTFILES_PATH"/bash/bashrc "$HOME"/.bashrc
ln -s "$DOTFILES_PATH"/bash/bash_aliases "$HOME"/.bash_aliases
ln -s "$DOTFILES_PATH"/bash/bash_profile "$HOME"/.bash_profile

# Fish
ln -s "$DOTFILES_PATH"/fish "$XDG_CONFIG_HOME"/fish
ln -s "$DOTFILES_PATH"/fish/fishfile "$HOME"/.fisher_plugins/fishfile

# ZSH
ln -s "$DOTFILES_PATH"/zsh/zshenv "$HOME"/.zshenv
ln -s "$DOTFILES_PATH"/zsh "$XDG_CONFIG_HOME"/zsh

# bat
ln -s "$DOTFILES_PATH"/bat "$XDG_CONFIG_HOME"/bat

# Rg
ln -s "$DOTFILES_PATH"/ripgrep/ripgreprc "$XDG_CONFIG_HOME"/ripgreprc

# Tmux
TMUX_COFIG_PATH="$DOTFILES_PATH/tmux"
ln -s "$TMUX_COFIG_PATH"/tmux.conf "$HOME"/tmux.conf
ln -s "$TMUX_COFIG_PATH"/tmuxinator "$HOME"/.tmuxinator

# Kitty
ln -s "$DOTFILES_PATH"/kitty "$XDG_CONFIG_HOME"/kitty

# Git
ln -s "$DOTFILES_PATH"/git/gitconfig "$HOME"/.gitconfig
ln -s "$DOTFILES_PATH"/git/gitconfig_riot "$HOME"/.gitconfig_riot

# Vim/NeoVim
ln -s "$DOTFILES_PATH"/vim "$HOME"/.vim
ln -s "$DOTFILES_PATH"/vim/vimrc "$HOME"/.vimrc
ln -s "$DOTFILES_PATH"/vim/gvimrc "$HOME"/.gvimrc
ln -s "$DOTFILES_PATH"/vim/ideavimrc "$HOME"/.ideavimrc
ln -s "$DOTFILES_PATH"/vim/init.vim "$XDG_CONFIG_HOME"/nvim/init.vim

# Executables
ln -s "$DOTFILES_PATH/bin" "$HOME/.bin"
