#!/usr/bin/env sh

DEV_PATH="$HOME/programming"
DOTFILES_PATH="$DEV_PATH/dotfiles"

# Bash
ln -s "$DOTFILES_PATH"/bash/bashrc "$HOME"/.bashrc
ln -s "$DOTFILES_PATH"/bash/bash_aliases "$HOME"/.bash_aliases
ln -s "$DOTFILES_PATH"/bash/bash_profile "$HOME"/.bash_profile

# Fish
ln -s "$DOTFILES_PATH"/fish "$XDG_CONFIG_HOME"/fish

# ZSH
ln -s "$DOTFILES_PATH"/zsh/zshenv "$HOME"/.zshenv
ln -s "$DOTFILES_PATH"/zsh "$XDG_CONFIG_HOME"/zsh

# bat
ln -s "$DOTFILES_PATH"/bat "$XDG_CONFIG_HOME"/bat

# Rg
ln -s "$DOTFILES_PATH"/ripgrep/ripgreprc "$XDG_CONFIG_HOME"/ripgreprc

# Kitty
ln -s "$DOTFILES_PATH"/kitty "$XDG_CONFIG_HOME"/kitty

# glrnvim
ln -s "$DOTFILES_PATH"/glrnvim "$XDG_CONFIG_HOME"/glrnvim

# Git
ln -s "$DOTFILES_PATH"/git/gitconfig "$HOME"/.gitconfig
ln -s "$DOTFILES_PATH"/git/gitconfig_riot "$HOME"/.gitconfig_riot

# Vim/NeoVim
ln -s "$DOTFILES_PATH"/vim "$HOME"/.vim
ln -s "$DOTFILES_PATH"/vim "$XDG_CONFIG_HOME"/nvim
ln -s "$DOTFILES_PATH"/vim/vimrc "$HOME"/.vimrc
ln -s "$DOTFILES_PATH"/vim/gvimrc "$HOME"/.gvimrc
ln -s "$DOTFILES_PATH"/vim/ideavimrc "$HOME"/.ideavimrc

# Executables
ln -s "$DOTFILES_PATH/bin" "$HOME/.bin"
