#!/usr/bin/env bash

# Launchctl script to remap caps on login
launchctl load ~/Library/LaunchAgents/com.user.loginscript.plist

# Install Golang and create GOPATH folders
# https://golang.org/dl/
mkdir -p $HOME/Development/go/src
mkdir -p $HOME/Development/go/bin
mkdir -p $HOME/Development/go/pkg


# Install homebrew (https://brew.sh/)
brew tap caskroom/drivers
brew tap caskroom/fonts

# Install with Cask:
brew cask install google-chrome
brew cask install sizeup
brew cask install iterm2
brew cask install atom # (package-sync for initial setup)
brew cask install google-backup-and-sync
brew cask install font-ubuntu
brew cask install docker
brew cask install franz
brew cask install dash
brew cask install bartender
brew cask install radiant-player
brew cask install logitech-options

# Install with brew:
brew install coreutils
brew install gnu-sed --with-default-names
brew install findutils --with-default-names
brew install gnu-tar --with-default-names
brew install gnu-which --with-default-names
brew install wget
brew install vim --with-override-system-vi
brew install less
brew install make --with-default-names
brew install n
brew install shellcheck
brew install fish
brew install git
brew install openssh
brew install diff-so-fancy
brew install the_silver_searcher
brew install autojump
brew install bash
brew install httpie
brew install awscli
brew install terraform
brew install python3
brew install pipenv
brew install exa
brew install tldr
brew install teensy_loader_cli

# Remove outdated versions from the cellar
brew cleanup

pip3 install bpython

# Stuff from App Store
# - MonthlyCal


# Add bash and fish to /etc/shells
echo '/usr/local/bin/fish' | sudo tee -a /etc/shells
echo '/usr/local/bin/bash' | sudo tee -a /etc/shells

# Set fish as default shell
chsh -s /usr/local/bin/fish


# Install Ubuntu font with ligatures - https://github.com/ToxicFrog/Ligaturizer
wget https://github.com/ToxicFrog/Ligaturizer/blob/master/output-fonts/LigaUbuntuMono-Regular.ttf -O ~/Library/Fonts/LigaUbuntuMono-Regular.ttf
