#!/usr/bin/env bash

# Install Golang and create GOPATH folders
# https://golang.org/dl/
mkdir -p "$HOME"/Development/go/src
mkdir -p "$HOME"/Development/go/bin
mkdir -p "$HOME"/Development/go/pkg

# Install homebrew (https://brew.sh/)
brew tap caskroom/drivers
brew tap caskroom/fonts
brew tap fisherman/tap

# Install with Cask:
brew cask install google-chrome
brew cask install sizeup
brew cask install google-backup-and-sync
brew cask install font-ubuntu
brew cask install font-symbola
brew cask install docker
brew cask install franz
brew cask install alfred
brew cask install bartender
brew cask install logitech-options
brew cask install kitty

# Install with brew:
brew install coreutils
brew install gnu-sed
brew install findutils
brew install gnu-tar
brew install gnu-which
brew install wget
brew install vim
brew install less
brew install make
brew install n
brew install git
brew install openssh
brew install diff-so-fancy
brew install ripgrep
brew install autojump
brew install fish
brew install bash
brew install zsh
brew install shellcheck
brew install shfmt
brew install checkbashisms
brew install httpie
brew install awscli
brew install terraform
brew install python3
brew install pipenv
brew install exa
brew install tldr
brew install teensy_loader_cli
brew install bat
brew install fd
brew install jetbrains-toolbox
brew install fzf
brew install jq
brew install yq
brew install dust

# Remove outdated versions from the cellar
brew cleanup

pip3 install bpython

# Stuff from App Store
# - MonthlyCal

# Add bash and fish to /etc/shells
echo '/usr/local/bin/fish' | sudo tee -a /etc/shells
echo '/usr/local/bin/bash' | sudo tee -a /etc/shells

# Set fish as default shell
chsh -s /usr/local/bin/fish

# Setup fzf completions and shortcuts for fish
"$(brew --prefix)"/opt/fzf/install

# Install Ubuntu font with ligatures - https://github.com/ToxicFrog/Ligaturizer
wget https://github.com/ToxicFrog/Ligaturizer/blob/master/output-fonts/LigaUbuntuMono-Regular.ttf -O ~/Library/Fonts/LigaUbuntuMono-Regular.ttf
