#!/usr/bin/env bash

# Hyper
ln -s $DOTFILES_PATH/hyper/.hyper_macos.js $HOME/.hyper.js

# ColemakDH-Matrix layout
ln -s $DOTFILES_PATH/keyboard/macos/ColemakDH-Matrix.bundle /Library/"Keyboard Layouts"/ColemakDH-Matrix.bundle

# Remap capslock to backspace
ln -s $DOTFILES_PATH/keyboard/macos/remap_caps.plist $HOME/Library/LaunchAgents/com.user.loginscript.plist
