#!/usr/bin/env bash

# Setup MacOS's NightShift
# Remove system shortcuts that will be used for something else:
#   - Mission Control > Move Left/Right a space - ^left/right
#   - Mission Control > Mission Control - ^up
#   - Mission Control > Application Windows - ^down
#   - Spotlight > Show Spotlight Search - cmd-space
#   - Spotlight > Show Finder search window - option-cmd-space

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Save screenshots to the Downloads folder
mkdir "$HOME"/Downloads/Screenshots
defaults write com.apple.screencapture location -string "$HOME/Downloads/screenshots"

# Ask for password immediately after lock
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Keyboard: Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Menu bar: Set preferred date format
defaults write com.apple.menuextra.clock DateFormat -string "EEE d MMM  HH:mm"

# Menu bar: Enable desired icons
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.volume" -int 1
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.clock" -int 1
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.battery" -int 1
defaults write com.apple.systemuiserver menuExtras -array \
  "/System/Library/CoreServices/Menu Extras/Battery.menu" \
  "/System/Library/CoreServices/Menu Extras/Clock.menu" \
  "/System/Library/CoreServices/Menu Extras/Volume.menu"

# Finder: Show hidden files by default
defaults write com.apple.Finder AppleShowAllFiles -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: Set Development as the default location for new Finder windows
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://$HOME/Development/"

# Dock: Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Dock: Set Auto Show/Hide Delay
defaults write com.apple.Dock autohide-delay -float 0
